[[languages.cpp.environments]]
CXX = "g++"
CXXFLAGS = ["-std=c++20", "-Wall", "-O2"]

[[languages.nim.environments]]
compile_to = "cpp"
NIMFLAGS = ["-d:release", "--opt:speed", "--multimethods:on", "--warning[SmallLshouldNotBeUsed]:off", "--hints:off"]